--create database fakulteti;

--create table ispitnirok(
--sifra int,
--predmet varchar(25),
--vrstaispita varchar(40),
--datum datetime,
--pristupio varchar(50)
--);
--create table pristupnici(
--ispitnirok datetime,
--student varchar(50),
--brojbodova int,
--ocjena int
--);
